title : 风笑痴
tagline: 一个脱离了低级懒惰的人
author :
  name : Lunny Xiao
  email : xiaolunwen@gmail.com
  github : lunny
  twitter : lunny

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
